---
title: heisen.me
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: assets/images
  values:
    image: true
permalink: "/:title/"
plugins:
- jekyll-sitemap
include:
- _pages
ga_id: UA-XXXXXXXX-1
url: https://heisen.me
about: heisen.me
keep_files:
- assets
twitter: evgenity_dev
email: meow@heisen.me
address:
- 3503 Jack Northrop Ave
- Hawthorne, CA 90250
telephone:
- "+1 805 2679658"
brand:
- heisen.me
